es6:
  path: http://10.100.218.28:9200
  dynamicIndex: true
  index: test-logs-x{yyyy}.x{MM}.x{dd}
  type: test-logs
  size: 1000
  query: |
    {
        "size":x{size},
        "sort":[
            {
                "messagetime":{
                    "order":"x{sort}"
                }
            }
        ],
        "_source":["message"],
        "query": {
           "bool": {
             "should": {
               "match_phrase": {
                 "logtid": "x{traceId}"
               }
             }
           }
        }
    }


server:
  port: 8083

logging:
  config: classpath:log4j2.xml

spring:
  application:
    name: log-viewer
  aop:
    proxy-target-class: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    check-template-location: true
    servlet:
      content-type: text/html
  cache:
    cache-names: dubboCache
    caffeine:
      spec: maximumSize=500,expireAfterAccess=60s


feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: BASIC
  okhttp:
    enabled: true

#swagger配置
swagger:
  enabled: true
  base-package: com.lsyf.pay.logger
  base-path: /**
  exclude-path: /error, /ops/**




