sw:
  path: http://192.168.132.96:12800/graphql
es6:
  path: http://192.168.132.110:9200
  dynamicIndex: true
  index: cashout-x{yyyy}.x{MM}.x{dd},testcashout-x{yyyy}.x{MM}.x{dd},docker-cashout-x{yyyy}.x{MM}.x{dd}

logging:
  config: classpath:log4j2-test.xml

log:
  env:
    cashout: SANDBOX
    testcashout: TEST